dist: xenial
language: node_js
node_js:
    - 'lts/*'
addons:
    chrome: stable
    firefox: latest
env:
    global:
        - NODE_ENV=test
        - BROWSER=chrome
branches:
    only:
        - master

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - source ~/.bashrc

install: make install

cache:
    yarn: true
    directories:
        - ~/.cache

script: make test

stages:
    - name: test
      if: branch = master

jobs:
    include:
        - stage: test
          name: Units and E2E tests
          env:
              - DEPLOY_ENV=test
              - NODE_ENV=test
